# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1af90d845b9391096e8dfc97ed7c4557b9fb47e57d49139e4f022ae2ad774b44e93e756cd3f6533dbd3e39893b98e3d0e8f5d050b2c38c0307e0c4eaa136bdf4

test:
  secret_key_base: cb5ea1e2e22147e99a33bf16c31247be0ea6a8b1d16d6c6186ad2c4567e131f7624624cfef06636d98c1357b7e33165d35ec7355aa2545ddc451724f317ad934

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
